EDPDEV-382 Fix join query with key_b
solvebio/solvebio-python pull request #432
Opened 2023-05-29 08:03 UTC by kuzentio

2023-05-30 16:21 UTC, davecap approved these changes

2023-05-31 16:31 UTC, nishanthmerwin requested changes
See comment here: https://github.com/solvebio/solvebio-python/pull/432/files#r1210661611

2023-06-02 13:24 UTC, nishanthmerwin commented on solvebio/test/test_query.py
> +            self.assertTrue('variant' in record)
New test looks great!

2023-06-02 13:25 UTC, nishanthmerwin approved these changes
New test looks great!

2023-06-02 13:26 UTC, merged