EDPDEV-896 Manage Shortcuts
solvebio/solvebio-python pull request #442
Opened 2023-10-11 14:19 UTC by nrasulicpfm

2023-10-11 18:10 UTC, davecap requested changes
Looks good, a few minor changes to consider

2023-10-12 13:02 UTC, nrasulicpfm commented on solvebio/resource/object.py
> +                pass
originally this was just 
```
except NotFoundError:
```

And that is working fine on vsim-dev. However when using qb-int-dev it raises a SolveError 404. That's why I added this to cover both not-found cases. But I'm not sure why this is different between the different environments - do you have an idea what could be the cause?

2023-10-12 13:05 UTC, nrasulicpfm commented on solvebio/resource/object.py
> +                                                         target=target)
sorry, left it out when refactoring to use create_by_full_path. Fixed.

2023-10-12 13:05 UTC, nrasulicpfm commented on solvebio/resource/object.py
> +            if isinstance(e, NotFoundError) or "404" in e.message:
fixed

2023-10-12 13:18 UTC, nrasulicpfm commented on solvebio/resource/object.py
> +            from . import Vault
yep this works. Added additional handling for the special case that shortcut target is None - though this should never be the case in a regular scenario

2023-10-25 14:33 UTC, davecap commented on solvebio/resource/object.py
> +                raise SolveError("Shortcut target is None.")
Change to `Shortcut target not found`

2023-10-25 14:33 UTC, davecap commented on solvebio/resource/object.py
> +                raise SolveError("Shortcut target is None.")
Do we have a case where `return_none_target` would be False?

2023-10-25 18:59 UTC, davecap commented
Overall looks good, just one more comment to address. Also need some docs to explain how to create and work with shortcuts. would be useful to also have a low level example that shows how to create a shortcut Object such as a URL.

2023-10-25 23:25 UTC, davecap approved these changes

2023-10-25 23:26 UTC, davecap commented
Going to merge this as it seems to be feature complete.

2023-10-25 23:26 UTC, merged